ALTER TABLE "Establishment" ADD COLUMN IF NOT EXISTS "primaryColor" TEXT DEFAULT '#2D6A4F';
ALTER TABLE "Establishment" ADD COLUMN IF NOT EXISTS "primaryDark" TEXT DEFAULT '#1B4332';
ALTER TABLE "Establishment" ADD COLUMN IF NOT EXISTS "primaryLight" TEXT DEFAULT '#D8F3DC';
ALTER TABLE "Establishment" ADD COLUMN IF NOT EXISTS "fontFamily" TEXT;
